import Head from "next/head";
import Image from "next/image";
import { Nav } from "../components/Nav";

export default function Home() {
  return (
    <div className="bg-blue-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />

      <main>
        <div className="h-screen">
          <div className="max-w-full h-full pb-4 mx-auto grid grid-cols-12 bg-blue-900">
            <div className="col-span-2 h-full mx-2 my-2 bg-gray-700 rounded-md">
              Placeholder Sidenav
            </div>
            <div className="col-span-8 h-full my-2 bg-gray-700 flex items-center rounded-md">
              <h1 className="mx-auto text-6xl font-bold">Main Content</h1>
            </div>
            <div className="col-span-2 h-full mx-2 my-2 bg-gray-700 rounded-md">
              Content Placeholder
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
