import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Nav } from '../../components/Nav';
import { MainDisplay } from '../../components/MainDisplay';
import {
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
  AuthAction,
} from 'next-firebase-auth';
import { getFirebaseAdmin } from 'next-firebase-auth';
import { ProfileDisplay } from '../../components/ProfileDisplay';

function Home() {
  const AuthUser = useAuthUser();

  return (
    <div className="bg-gray-200">
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav email={AuthUser.email} signOut={AuthUser.signOut} />

      <main>
        <MainDisplay />
      </main>
    </div>
  );
}

export const getServerSideProps = withAuthUserTokenSSR()(
  async ({ AuthUser }) => {
    const user = await getFirebaseAdmin().auth().getUserByEmail(AuthUser.email);
    if (user.email == 'lmsplatformcscix691@gmail.com') {
      if (user.customClaims && user.customClaims.admin == true) {
        console.log('user is admin');
        return;
      }
      return getFirebaseAdmin().auth().setCustomUserClaims(user.uid, {
        admin: true,
      });
    } else {
      console.log('user is student');
      return getFirebaseAdmin().auth().setCustomUserClaims(user.uid, {
        student: true,
      });
    }
  }
);

export default withAuthUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
  authPageURL: '/',
})(Home);
